#!/bin/ksh
#
# Copyright (c) 2020 - 2026 Matthias Pressfreund
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

srcroot='/usr/src'
srcdir=${srcroot}/usr.sbin/httpd
chksum0='8ef2a38c2afaf5a9d9f784609401b9fe23d40d0a6bc37da71e4dc16c5ea15f00'
chksum1='4e907a1da8e38255647d6f46865f42b5d16a75c8fb1d70be092591800530f5ba'

restore()
{
	echo -n 'Restoring original sources ... '
	cd ${srcdir}/..
	rm -rf ${srcdir} && mv $1 ${srcdir}
	(($? == 0)) && echo 'Done.' || echo 'Failed.'
}

if (($(id -u) != 0)); then
	echo 'Need root privileges.'
	exit 1
fi
if [[ ! -d ${srcdir} ]]; then
	echo 'Missing source tree.'
	exit 1
fi

chksum=$(find ${srcdir} \( -name '*.[chy578]' -o -name '*.in' \
    -o -name '*.sed' -o -name 'Makefile' \) -type f -maxdepth 1 -exec sha256 \
    -q {} \; | sort | sha256)
if [[ ${chksum0} != ${chksum} && ${chksum1} != ${chksum} ]]; then
	echo 'Sources and patches do not match. Make sure ...'
	echo '  ... the 7.8-stable branch is in use.'
	echo '  ... both are up-to-date.'
	while :
	do
		echo -n 'Continue anyway (Not recommended!)? [y/N] '
		read yn
		case ${yn} in
			y)	break;;
			*)	echo 'Exiting.'; exit 1;;
		esac
	done
fi

echo -n 'Backing up original sources ... '
while :
do
	bakdir=${srcdir}~$RANDOM
	[[ -d ${bakdir} ]] || break
done
cp -a ${srcdir} ${bakdir}
if (($? == 0)); then
	echo 'Done.'
else
	echo 'Failed.'
	exit 1
fi

echo 'Applying patch files ...'
for f in $(find $(pwd)/$(dirname $0) -type f -name '*.patch' | sort); do
	addon=$(basename ${f} .patch)
	len=$((${#addon}+10))
	printf "%${len}s\n" | tr ' ' '='
	printf '===  %s  ===\n' "${addon}"
	printf "%${len}s\n" | tr ' ' '='
	patch -d ${srcroot} -f -i ${f} -p0 --posix
	if (($? != 0)); then
		restore ${bakdir}
		exit 1
	fi
done

cd ${srcdir}

echo 'Building and installing httpd-plus binary and manpage ...'
make clean && make obj && make && make install
ret=$?

restore ${bakdir}

if ((ret != 0)); then
	echo "\nInstalling httpd-plus failed (exitcode: ${ret})."
	exit 1
fi
echo '\nInstalling httpd-plus binary and manpage completed successfully.'
echo "Please consult 'man httpd.conf' for further information on new features."
